CREATE DATABASE IF NOT EXISTS Security;

USE Security;

CREATE TABLE IF NOT EXISTS User (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Fullname VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    pass VARCHAR(50) NOT NULL
);
